/* GainForward — mock employee/participant dataset.
   Schema follows the SOP "Participant Profile" (Section 16) plus the roadmap
   extension fields called out for the AI-powered dashboard (division, tenure,
   geography, engagement status). Swap this seed for live data once the AI
   data source is configured in Settings (see js/api.js). */

const SEED_EMPLOYEES = [
  {
    id: "e-kapoor",
    fullName: "Arjun Kapoor",
    displayName: "A. Kapoor",
    avatarInitials: "AK",
    email: "arjun.kapoor@rategain.com",
    department: "Product",
    division: "Product & Engineering",
    careerLevel: "L5 — Director",
    tenureBand: "5+ yrs",
    geography: "APAC",
    learningGoals: ["Board-level storytelling"],
    offeredSkills: ["Product strategy", "Roadmap prioritization", "Discovery frameworks"],
    experience: "12 years in B2B SaaS product leadership, RG Rev Max suite",
    goalStatement: "Sharpen how I frame roadmap trade-offs to non-product execs",
    purpose: "Wants to mentor to reconnect with early-career craft",
    interests: ["AI-assisted PM workflows"],
    preferredFormat: "mentor",
    aiConfidence: "Practitioner",
    availability: { frequency: "Bi-weekly", timezone: "IST (UTC+5:30)", windows: "Mon/Wed mornings" },
    matchNote: "Happy to mentor across any function",
    engagementStatus: "active",
    rating: 4.9,
    menteeCount: 6,
    consentAck: true,
  },
  {
    id: "e-meyer",
    fullName: "Sofia Meyer",
    displayName: "S. Meyer",
    avatarInitials: "SM",
    email: "sofia.meyer@rategain.com",
    department: "Revenue Management",
    division: "Revenue Management",
    careerLevel: "L4 — Principal",
    tenureBand: "5+ yrs",
    geography: "EMEA",
    learningGoals: ["Cross-cultural leadership"],
    offeredSkills: ["Revenue forecasting", "Pricing strategy", "Executive communication"],
    experience: "Revenue strategy for EMEA hotel groups, ex-consulting",
    goalStatement: "Practice leading through influence outside direct authority",
    purpose: "Believes in paying forward mentorship she received early in her career",
    interests: ["AI forecasting models"],
    preferredFormat: "mentor",
    aiConfidence: "Advanced",
    availability: { frequency: "Bi-weekly", timezone: "CET (UTC+1)", windows: "Tue/Thu afternoons" },
    matchNote: "",
    engagementStatus: "active",
    rating: 5.0,
    menteeCount: 9,
    consentAck: true,
  },
  {
    id: "e-alonso",
    fullName: "Javier Alonso",
    displayName: "J. Alonso",
    avatarInitials: "JA",
    email: "javier.alonso@rategain.com",
    department: "Data Science",
    division: "Product & Engineering",
    careerLevel: "L4 — Principal",
    tenureBand: "3-5 yrs",
    geography: "LATAM",
    learningGoals: ["People management"],
    offeredSkills: ["ML model deployment", "Demand forecasting", "AI experimentation"],
    experience: "Applied ML for pricing and demand signals",
    goalStatement: "Learn to manage a team of ICs, not just projects",
    purpose: "Wants to build a bench of AI-confident mentees",
    interests: ["Cross-functional mentoring"],
    preferredFormat: "mentor",
    aiConfidence: "Advanced",
    availability: { frequency: "Monthly", timezone: "BRT (UTC-3)", windows: "Fri mornings" },
    matchNote: "",
    engagementStatus: "available",
    rating: 4.8,
    menteeCount: 4,
    consentAck: true,
  },
  {
    id: "e-osei",
    fullName: "Tariro Osei",
    displayName: "T. Osei",
    avatarInitials: "TO",
    email: "tariro.osei@rategain.com",
    department: "Customer Experience",
    division: "CX",
    careerLevel: "L4 — Principal",
    tenureBand: "5+ yrs",
    geography: "EMEA",
    learningGoals: ["Data storytelling"],
    offeredSkills: ["Customer success playbooks", "Escalation management", "Coaching"],
    experience: "Led CX for enterprise hotel chains across EMEA",
    goalStatement: "Get sharper with data to back up customer health narratives",
    purpose: "Mentoring keeps me close to how the org actually feels day to day",
    interests: ["Reverse mentoring"],
    preferredFormat: "mentor",
    aiConfidence: "Familiar",
    availability: { frequency: "Bi-weekly", timezone: "GMT (UTC+0)", windows: "Wed afternoons" },
    matchNote: "",
    engagementStatus: "active",
    rating: 4.9,
    menteeCount: 7,
    consentAck: true,
  },
  {
    id: "e-nair",
    fullName: "Devika Nair",
    displayName: "D. Nair",
    avatarInitials: "DN",
    email: "devika.nair@rategain.com",
    department: "MarTech",
    division: "MarTech",
    careerLevel: "L2 — Associate",
    tenureBand: "0-2 yrs",
    geography: "APAC",
    learningGoals: ["Campaign analytics", "Public speaking"],
    offeredSkills: ["Social content", "Community management"],
    experience: "2 years in brand marketing, fresh from Sojern integration team",
    goalStatement: "Build confidence presenting campaign results to APAC leadership",
    purpose: "New to the org and wants a peer connection across the merger",
    interests: ["AI content tools"],
    preferredFormat: "mentee",
    aiConfidence: "Beginner",
    availability: { frequency: "Bi-weekly", timezone: "IST (UTC+5:30)", windows: "Flexible" },
    matchNote: "Prefer another MarTech voice given the Sojern integration",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-fischer",
    fullName: "Lukas Fischer",
    displayName: "L. Fischer",
    avatarInitials: "LF",
    email: "lukas.fischer@rategain.com",
    department: "Engineering",
    division: "Product & Engineering",
    careerLevel: "L3 — Senior",
    tenureBand: "3-5 yrs",
    geography: "EMEA",
    learningGoals: ["Public speaking", "Cross-team collaboration"],
    offeredSkills: ["Distributed systems", "API design"],
    experience: "Platform engineering for RG's rate distribution APIs",
    goalStatement: "Get comfortable presenting architecture decisions to non-engineers",
    purpose: "Curious about reverse mentoring a junior PM on technical fluency",
    interests: ["Reverse mentoring", "AI pair-programming"],
    preferredFormat: "reverse",
    aiConfidence: "Advanced",
    availability: { frequency: "Bi-weekly", timezone: "CET (UTC+1)", windows: "Thu mornings" },
    matchNote: "",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-rossi",
    fullName: "Giulia Rossi",
    displayName: "G. Rossi",
    avatarInitials: "GR",
    email: "giulia.rossi@rategain.com",
    department: "Sales",
    division: "Commercial",
    careerLevel: "L3 — Senior",
    tenureBand: "3-5 yrs",
    geography: "EMEA",
    learningGoals: ["Revenue forecasting basics", "AI in sales workflows"],
    offeredSkills: ["Enterprise negotiation", "Deal strategy"],
    experience: "Enterprise sales across EMEA hospitality accounts",
    goalStatement: "Understand forecasting well enough to co-present with Rev Mgmt",
    purpose: "",
    interests: ["Peer learning circles"],
    preferredFormat: "peer",
    aiConfidence: "Familiar",
    availability: { frequency: "Monthly", timezone: "CET (UTC+1)", windows: "Fri afternoons" },
    matchNote: "",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-castillo",
    fullName: "Mateo Castillo",
    displayName: "M. Castillo",
    avatarInitials: "MC",
    email: "mateo.castillo@rategain.com",
    department: "Data Science",
    division: "Product & Engineering",
    careerLevel: "L2 — Associate",
    tenureBand: "0-2 yrs",
    geography: "LATAM",
    learningGoals: ["ML model deployment", "People management"],
    offeredSkills: ["Python tooling", "Dashboarding"],
    experience: "1.5 years, analytics for LATAM demand forecasting",
    goalStatement: "Ship my first production ML model with a mentor's guidance",
    purpose: "",
    interests: ["AI experimentation"],
    preferredFormat: "mentee",
    aiConfidence: "Beginner",
    availability: { frequency: "Bi-weekly", timezone: "BRT (UTC-3)", windows: "Flexible" },
    matchNote: "",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-thompson",
    fullName: "Hannah Thompson",
    displayName: "H. Thompson",
    avatarInitials: "HT",
    email: "hannah.thompson@rategain.com",
    department: "People Development",
    division: "People & Culture",
    careerLevel: "L4 — Principal",
    tenureBand: "5+ yrs",
    geography: "NA",
    learningGoals: ["AI in people analytics"],
    offeredSkills: ["Program design", "Facilitation", "Coaching"],
    experience: "Owns the GainForward pilot design and SOP",
    goalStatement: "",
    purpose: "PD lead — facilitates the ecosystem, matching and pulse checks",
    interests: ["AI Maturity Pathway"],
    preferredFormat: "mentor",
    aiConfidence: "Practitioner",
    availability: { frequency: "Bi-weekly", timezone: "ET (UTC-5)", windows: "Mon/Wed afternoons" },
    matchNote: "",
    engagementStatus: "active",
    rating: 4.7,
    menteeCount: 3,
    consentAck: true,
    isPDAdmin: true,
  },
  {
    id: "e-singh",
    fullName: "Kabir Singh",
    displayName: "K. Singh",
    avatarInitials: "KS",
    email: "kabir.singh@rategain.com",
    department: "Finance",
    division: "Finance",
    careerLevel: "L3 — Senior",
    tenureBand: "3-5 yrs",
    geography: "APAC",
    learningGoals: ["Cross-team collaboration", "Executive communication"],
    offeredSkills: ["FP&A", "Deal economics"],
    experience: "FP&A support for MarTech division post-acquisition",
    goalStatement: "Build a peer network outside Finance to understand MarTech better",
    purpose: "",
    interests: ["Peer learning circles"],
    preferredFormat: "peer",
    aiConfidence: "Familiar",
    availability: { frequency: "Monthly", timezone: "IST (UTC+5:30)", windows: "Tue mornings" },
    matchNote: "Prefer someone outside my function",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-oyelaran",
    fullName: "Ade Oyelaran",
    displayName: "A. Oyelaran",
    avatarInitials: "AO",
    email: "ade.oyelaran@rategain.com",
    department: "Customer Experience",
    division: "CX",
    careerLevel: "L2 — Associate",
    tenureBand: "0-2 yrs",
    geography: "EMEA",
    learningGoals: ["Data storytelling", "Escalation management"],
    offeredSkills: ["Client onboarding"],
    experience: "1 year, onboarding specialist for EMEA mid-market accounts",
    goalStatement: "Learn to handle escalations calmly and confidently",
    purpose: "",
    interests: [],
    preferredFormat: "mentee",
    aiConfidence: "Beginner",
    availability: { frequency: "Bi-weekly", timezone: "GMT (UTC+0)", windows: "Wed afternoons" },
    matchNote: "",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-park",
    fullName: "Jiwoo Park",
    displayName: "J. Park",
    avatarInitials: "JP",
    email: "jiwoo.park@rategain.com",
    department: "Product",
    division: "Product & Engineering",
    careerLevel: "L2 — Associate",
    tenureBand: "0-2 yrs",
    geography: "APAC",
    learningGoals: ["Product strategy", "Discovery frameworks"],
    offeredSkills: ["User research"],
    experience: "1.5 years, associate PM on the distribution platform",
    goalStatement: "Learn how senior PMs prioritize under ambiguity",
    purpose: "",
    interests: ["AI-assisted PM workflows"],
    preferredFormat: "mentee",
    aiConfidence: "Familiar",
    availability: { frequency: "Bi-weekly", timezone: "IST (UTC+5:30)", windows: "Mon/Wed mornings" },
    matchNote: "",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
  {
    id: "e-diallo",
    fullName: "Amara Diallo",
    displayName: "A. Diallo",
    avatarInitials: "AD",
    email: "amara.diallo@rategain.com",
    department: "MarTech",
    division: "MarTech",
    careerLevel: "L3 — Senior",
    tenureBand: "3-5 yrs",
    geography: "EMEA",
    learningGoals: ["AI in marketing", "Revenue management"],
    offeredSkills: ["Marketing ops", "Lifecycle marketing"],
    experience: "3.5 years, marketing ops across the Sojern integration",
    goalStatement: "Get fluent enough in AI tooling to lead a pilot in my team",
    purpose: "",
    interests: ["AI in marketing"],
    preferredFormat: "peer",
    aiConfidence: "Familiar",
    availability: { frequency: "Bi-weekly", timezone: "CET (UTC+1)", windows: "Thu afternoons" },
    matchNote: "",
    engagementStatus: "available",
    rating: null,
    menteeCount: 0,
    consentAck: true,
  },
];

/* Demo login — this is a static, backend-free prototype, so these are NOT
   real secured accounts: the username/password check runs entirely in this
   client-side JS, visible to anyone who opens dev tools. They exist purely
   so a handful of testers can each land in a distinct, pre-built scenario
   without colliding in the same shared deployment. Don't reuse this pattern
   for anything beyond a trusted-tester demo. */
const DEMO_ACCOUNTS = [
  {
    username: "mentor1",
    password: "Demo@2026",
    id: "demo-mentor-1",
    scenario: "An experienced mentor with mentees already — good for exploring the Directory from the other side, and the Admin matching queue.",
    employee: {
      fullName: "Priya Nair", displayName: "P. Nair", avatarInitials: "PN", email: "priya.nair@demo.gainforward.app",
      department: "Customer Experience", division: "CX", careerLevel: "L4 — Principal", tenureBand: "5+ yrs", geography: "EMEA",
      learningGoals: [], offeredSkills: ["Client escalation handling", "Coaching new CSMs"],
      experience: "8 years leading enterprise CX for EMEA hotel groups",
      goalStatement: "", purpose: "I want to help newer CSMs build confidence handling tough accounts.", skillLevel: "",
      interests: [], preferredFormat: "mentor", aiConfidence: "Practitioner",
      availability: { frequency: "Bi-weekly", timezone: "GMT (UTC+0)", windows: "Wed afternoons" },
      matchNote: "", engagementStatus: "available", rating: 4.8, menteeCount: 2, consentAck: true, profileComplete: true,
    },
  },
  {
    username: "mentee1",
    password: "Demo@2026",
    id: "demo-mentee-1",
    scenario: "A fresh mentee with no journey yet — good for exploring Directory search, sending a request, and the Admin approval flow from scratch.",
    employee: {
      fullName: "Sam Ortiz", displayName: "S. Ortiz", avatarInitials: "SO", email: "sam.ortiz@demo.gainforward.app",
      department: "Sales", division: "Commercial", careerLevel: "L2 — Associate", tenureBand: "0-2 yrs", geography: "NA",
      learningGoals: ["Negotiation tactics", "Deal storytelling"], offeredSkills: [],
      experience: "1.5 years in enterprise sales",
      goalStatement: "Close my first enterprise deal narrative with confidence.", purpose: "", skillLevel: "Beginner",
      interests: [], preferredFormat: "mentee", aiConfidence: "Familiar",
      availability: { frequency: "Bi-weekly", timezone: "ET (UTC-5)", windows: "Flexible" },
      matchNote: "", engagementStatus: "available", rating: null, menteeCount: 0, consentAck: true, profileComplete: true,
    },
  },
  {
    username: "mentee2",
    password: "Demo@2026",
    id: "demo-mentee-2",
    scenario: "A mentee already partway through an active journey — good for exploring My Journey, calendar scheduling, nudges, and Insights with real data already in place.",
    employee: {
      fullName: "Jordan Blake", displayName: "J. Blake", avatarInitials: "JB", email: "jordan.blake@demo.gainforward.app",
      department: "MarTech", division: "MarTech", careerLevel: "L3 — Senior", tenureBand: "3-5 yrs", geography: "APAC",
      learningGoals: ["Executive communication", "Revenue forecasting"], offeredSkills: ["Campaign analytics"],
      experience: "Marketing automation, lifecycle campaigns",
      goalStatement: "Present forecasts to leadership with confidence within 12 weeks", purpose: "", skillLevel: "Intermediate",
      interests: [], preferredFormat: "mentee", aiConfidence: "Familiar",
      availability: { frequency: "Bi-weekly", timezone: "IST (UTC+5:30)", windows: "Tue/Thu afternoons" },
      matchNote: "", engagementStatus: "active", rating: null, menteeCount: 0, consentAck: true, profileComplete: true,
    },
  },
  {
    username: "admin1",
    password: "Demo@2026",
    id: "demo-admin-1",
    scenario: "The PD/program-admin persona — good for exploring the Admin console: matching queue, roster, decision gates.",
    employee: {
      fullName: "Morgan Lee", displayName: "M. Lee", avatarInitials: "ML", email: "morgan.lee@demo.gainforward.app",
      department: "People Development", division: "People & Culture", careerLevel: "L4 — Principal", tenureBand: "5+ yrs", geography: "NA",
      learningGoals: [], offeredSkills: ["Program facilitation", "Coaching"],
      experience: "Runs the GainForward pilot end to end",
      goalStatement: "", purpose: "I own the pilot design and review every proposed match.", skillLevel: "",
      interests: [], preferredFormat: "mentor", aiConfidence: "Practitioner",
      availability: { frequency: "Bi-weekly", timezone: "ET (UTC-5)", windows: "Mon/Wed afternoons" },
      matchNote: "", engagementStatus: "active", rating: 4.7, menteeCount: 1, consentAck: true, profileComplete: true,
    },
  },
  {
    username: "newuser1",
    password: "Demo@2026",
    id: "demo-new-1",
    scenario: "A brand-new employee who hasn't set up a profile yet — good for showing the mandatory onboarding screen and the two \"I want to become a...\" flows.",
    employee: {
      fullName: "", displayName: "", avatarInitials: "", email: "",
      department: "", division: "", careerLevel: "", tenureBand: "", geography: "",
      learningGoals: [], offeredSkills: [], experience: "", goalStatement: "", purpose: "", skillLevel: "",
      interests: [], preferredFormat: "", aiConfidence: "",
      availability: { frequency: "", timezone: "", windows: "" },
      matchNote: "", engagementStatus: "available", rating: null, menteeCount: 0, consentAck: false, profileComplete: false,
    },
  },
];

// Matching-weight rationale, decision gates, KPI targets and pilot artefacts
// straight from the SOP — kept as data so the Insights/Admin views render
// their targets/labels from one source of truth instead of hardcoded markup.
const PROGRAM_META = {
  cohortTarget: { min: 50, max: 75 },
  pilotWeeks: 12,
  stages: [
    { key: "connect", label: "Connect", weekStart: 1, weekEnd: 2, detail: "Build trust and set expectations" },
    { key: "goal", label: "Goal", weekStart: 2, weekEnd: 3, detail: "Agree the learning and contribution focus" },
    { key: "challenge", label: "Challenge", weekStart: 3, weekEnd: 8, detail: "Work through a real situation or case" },
    { key: "apply", label: "Apply", weekStart: 6, weekEnd: 10, detail: "Try one workplace action or AI experiment" },
    { key: "transfer", label: "Transfer", weekStart: 10, weekEnd: 12, detail: "Close out, continue, or share what you learned" },
  ],
  matchWeights: [
    { key: "goal", label: "Learning goal ↔ expertise", weight: 0.40 },
    { key: "complement", label: "Complementary perspective", weight: 0.20 },
    { key: "format", label: "Format & preference fit", weight: 0.15 },
    { key: "availability", label: "Availability / time zone", weight: 0.15 },
    { key: "other", label: "Other preferences", weight: 0.10 },
  ],
  matchChecklist: [
    "Can we explain in one sentence why these two people should meet?",
    "Does the mentor's expertise credibly address the learning goal?",
    "Is there a conflict of interest or reporting relationship between them?",
    "Can both parties realistically meet on a recurring cadence?",
    "Does the proposed format match both people's stated preference?",
    "Would this pairing add a genuinely different perspective for the learner?",
  ],
  kpis: {
    adoption: [
      { key: "profiles", label: "Profiles created", target: 0.80, format: "percent" },
      { key: "connections", label: "Connections started", target: 30, format: "count" },
      { key: "requests", label: "Connection requests", target: null, format: "count" },
    ],
    relationshipQuality: [
      { key: "health", label: "Relationship health (avg / 5)", target: 4.0, format: "score" },
      { key: "meaningful", label: "Meaningful conversations", target: 0.70, format: "percent" },
      { key: "continuation", label: "Continuation beyond pilot", target: 0.50, format: "percent" },
    ],
    learningImpact: [
      { key: "goalClarity", label: "Goal clarity by Week 2", target: 0.90, format: "percent" },
      { key: "application", label: "Workplace application", target: 0.60, format: "percent" },
      { key: "peerShared", label: "Peer learning shared", target: 0.25, format: "percent" },
    ],
  },
  decisionGates: [
    { key: "gate0", label: "Gate 0 — Design", question: "Are hypotheses and boundaries clear?" },
    { key: "gate1", label: "Gate 1 — Ready", question: "Enough participants and viable matches?" },
    { key: "gate2", label: "Gate 2 — Midpoint", question: "Is the experience healthy enough to continue?" },
    { key: "gate3", label: "Gate 3 — Close", question: "Did the pilot create enough value to justify iteration?" },
  ],
};

/* Learning Resources — content for the tabbed resources modal.
   LinkedIn Learning entries are real, existing courses (verified titles,
   instructors, and URLs) commonly included in enterprise LinkedIn Learning
   subscriptions — search the title in your org's LinkedIn Learning portal
   to confirm your own access, since exact catalog contents vary by tier. */
const RESOURCE_LIBRARY = {
  faqs: [
    {
      q: "How long does a mentoring relationship last?",
      a: "The pilot runs 12 weeks, with five core conversations roughly every two weeks. Many pairs choose to continue informally after that.",
    },
    {
      q: "Is participation mandatory?",
      a: "No — it's entirely voluntary. You can pause or end a connection at any time without needing to justify it.",
    },
    {
      q: "What if my mentor or mentee and I aren't clicking?",
      a: "Request a no-fault rematch from your Journey page. Nobody has to explain why — that's built into the program on purpose, not an exception to it.",
    },
    {
      q: "Can I be both a mentor and a mentee?",
      a: "Yes. Plenty of people mentor in one area and are mentored in another — that's the whole idea behind \"everyone has something to learn, everyone has something to contribute.\"",
    },
    {
      q: "Does this affect my performance review?",
      a: "No. GainForward is explicitly not a performance-management tool — conversations here are confidential and separate from any formal review process, and won't be used to make career or promotion decisions.",
    },
    {
      q: "What if I don't have much time?",
      a: "Sessions are short by design — 30–60 minutes every two weeks. Even four conversations plus one real workplace application counts as a meaningful cycle.",
    },
    {
      q: "Do I need my manager's approval to participate?",
      a: "No formal approval is required, though it's good practice to let your manager know, especially if sessions happen during work hours.",
    },
    {
      q: "What happens after the 12 weeks end?",
      a: "You and your partner decide together — continue informally, end the formal relationship, or become a peer-learning contributor sharing what you learned with others.",
    },
  ],

  bestPractices: [
    "Match on specific goals and skills, not just seniority — the best pairings are about fit, not hierarchy.",
    "Set ground rules in your very first conversation: cadence, confidentiality, and how you'll handle a reschedule.",
    "Put a recurring slot on the calendar rather than \"find time when we can\" — momentum matters more than session length.",
    "Treat it as a two-way exchange. Even senior mentors usually learn something back.",
    "Check in on how the relationship itself is going, not just the topics — a quick pulse catches problems early.",
    "Close the loop. A relationship that ends with a short reflection produces more value than one that just fades out.",
  ],

  mentorTips: [
    "Listen more than you advise — ask what they've already tried before offering your own solution.",
    "Share the reasoning behind your experience, not just the outcome — the \"why,\" not just \"what I'd do.\"",
    "Keep what's shared confidential, especially anything about performance or workplace friction.",
    "Let your mentee set the agenda. You're there to guide, not to direct.",
    "Be honest about what you don't know — mentoring isn't the same as having every answer.",
    "Give specific, evidence-based feedback rather than general encouragement.",
    "Expect nothing in return. This isn't a two-way obligation.",
  ],

  menteeTips: [
    "Come with a specific goal, not just \"I want general career advice\" — specificity gets you sharper help.",
    "Own the relationship — schedule the sessions, set the agenda, and follow up afterward.",
    "Do the work between sessions. A mentor can point the way; only you can walk it.",
    "Ask the question behind the question — a bit of context helps your mentor give a better answer.",
    "Be open to feedback that isn't what you expected to hear.",
    "Respect your mentor's time — show up prepared, and reschedule early if you need to.",
  ],

  dos: [
    "Put a recurring slot on the calendar",
    "Come with a specific topic or question each time",
    "Say so early if the format or cadence isn't working",
    "Keep the conversation confidential",
    "Follow through on whatever you agreed to try",
    "End the cycle with a short reflection, even an informal one",
  ],
  donts: [
    "Treat it as a one-off \"pick your brain\" session",
    "Wait for the other person to drive every conversation",
    "Turn it into a performance review or a complaints channel",
    "Ghost — if you need to step back, just say so",
    "Expect a mentor to have every answer",
    "Skip the first \"getting to know you\" conversation to save time — it's what makes the rest work",
  ],

  makingTheMost: [
    { phase: "Before", tip: "Send a short agenda the day before — even three bullet points signals you're prepared and gives your partner time to think." },
    { phase: "Start", tip: "Spend the first few minutes on rapport, not straight into business — trust is what makes the advice land." },
    { phase: "End", tip: "Leave the last five minutes for \"what will I actually try before we next meet?\"" },
    { phase: "After", tip: "Send a one-line follow-up on what you took away or tried — it closes the loop and builds momentum for next time." },
    { phase: "Ongoing", tip: "Revisit your goal every few sessions — it's fine for it to evolve as you learn more about what you actually need." },
  ],

  linkedinCourses: [
    { title: "Being a Good Mentor", instructor: "Ellen Ensher", note: "Building trust, structuring meetings, and giving feedback as a mentor.", url: "https://www.linkedin.com/learning/being-a-good-mentor" },
    { title: "Being a Good Mentee", instructor: "Ellen Ensher", note: "Finding and connecting with mentors, and owning the relationship.", url: "https://www.linkedin.com/learning/being-a-good-mentee" },
    { title: "How to Be a Good Mentee and Mentor", instructor: "Emilie Aries", note: "Roles, expectations, and nurturing the relationship from both sides.", url: "https://www.linkedin.com/learning/how-to-be-a-good-mentee-and-mentor" },
    { title: "Coaching and Developing Employees", instructor: "Lisa Gates", note: "Asking better questions, listening, and growing someone's autonomy.", url: "https://www.linkedin.com/learning/coaching-and-developing-employees-5" },
    { title: "Giving and Receiving Feedback", instructor: "Dr. Gemma Leigh Roberts", note: "The psychology of feedback that actually lands.", url: "https://www.linkedin.com/learning/giving-and-receiving-feedback-18926015" },
    { title: "Having Difficult Conversations", instructor: "Marlene Chism", note: "For when a mentoring conversation needs to get real.", url: "https://www.linkedin.com/learning/having-difficult-conversations-2018" },
  ],
};
